from python:2.7
run pip install flask
run pip install newrelic
add src/main/python /code
add  newrelic.ini  /code
workdir /code
env NEW_RELIC_CONFIG_FILE newrelic.ini
cmd ["newrelic-admin","run-program","python","-m","chengducloud.wuhouapp"] 

